import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles/index.css'
import App from './App.tsx'
import { SettingsProvider } from './contexts/SettingsContext'

// Register service worker for PWA functionality
// In production build, sw.js is generated by vite-plugin-pwa
// In development, we skip service worker registration
if ('serviceWorker' in navigator && window.location.protocol !== 'file:') {
  window.addEventListener('load', () => {
    // Only register service worker in production mode
    if (import.meta.env.PROD) {
      const swUrl = `/sw.js`
      navigator.serviceWorker
        .register(swUrl)
        .then((registration) => {
          console.log('Service Worker registered: ', registration)

          // Check for service worker updates
          registration.addEventListener('updatefound', () => {
            const newWorker = registration.installing
            if (newWorker) {
              newWorker.addEventListener('statechange', () => {
                if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                  // New content available
                  if (confirm('New content available. Reload to update?')) {
                    window.location.reload()
                  }
                }
              })
            }
          })
        })
        .catch((error: Error) => {
          console.error('Service Worker registration failed: ', error)
        })
    } else {
      console.log('Service Worker registration skipped in development mode')
    }
  })
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <SettingsProvider>
      <App />
    </SettingsProvider>
  </StrictMode>,
)
